name: NodeJS with Webpack

on:
  push:
    branches: [ "feature/actions-releases" ]
  pull_request:
    branches: [ "feature/actions-releases" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Build AppImage
      run: |
        npm ci
        npm run build:linux

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: chubu-linux-appimage
        path: dist/*.AppImage
        if-no-files-found: error

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Build NSIS installer
      run: |
        npm ci
        npm run build:win

    - name: Upload Windows installer
      uses: actions/upload-artifact@v4
      with:
        name: chubu-windows-installer
        path: dist/*.exe
        if-no-files-found: error
